networks:
  default_network:
    driver: bridge

services:
  payments-ms:
    build: .
    ports:
      - '3000:3000'
    volumes:
      - ./src:/usr/src/app/src
    command: npm run start:dev
    env_file:
      - .env
    networks:
      - default_network

  stripe-cli:
    image: stripe/stripe-cli
    container_name: stripe-cli
    command: 'listen --api-key ${STRIPE_SECRET} --device-name ${STRIPE_DEVICE_NAME} --forward-to http://payments-ms:${PORT}/payments/hook/'
    env_file:
      - .env
    networks:
      - default_network
